<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.3" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
    <PackageReference Include="SixLabors.ImageSharp" Version="4.1.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../MAM.Application/MAM.Application.csproj" />
    <ProjectReference Include="../MAM.Domain/MAM.Domain.csproj" />
  </ItemGroup>
</Project>