using System.Security.Cryptography;
using System.Text.Json;
using MAM.Application.Discovery;
using MAM.Application.Storage;
using MAM.Infrastructure.Configuration;
using Microsoft.Data.Sqlite;

namespace MAM.Infrastructure.Demo;

public sealed class DemoVisualSearchService(
    DemoSqliteDatabase database,
    IStorageObjectStore primary,
    IVisualEmbeddingProvider provider,
    MamSettings settings) : IVisualSearchService
{
    private readonly string _derivativesPrefix = CleanPrefix(settings.Storage.Primary.DerivativesPrefix, "derivatives");

    public async Task<VisualSearchHealth> GetHealthAsync(CancellationToken cancellationToken = default)
    {
        await EnsureSchemaAsync(cancellationToken);
        var health = provider.Health;
        return new VisualSearchHealth(health.IsReady, health.Provider, health.ModelId, health.ModelVersion, health.Dimensions,
            health.IsReady ? "Offline Demo visual index is ready." : health.Detail);
    }

    public async Task<IReadOnlyList<VisualSegmentSnapshot>> ListSegmentsAsync(Guid assetId, string sourceKind, CancellationToken cancellationToken = default)
    {
        await EnsureSchemaAsync(cancellationToken); sourceKind=NormalizeSource(sourceKind);
        var text=await ReadTextAsync(assetId,sourceKind,cancellationToken); if(text is null)return [];
        var visual=new Dictionary<int,VisualRow>();await using(var c=await database.OpenAsync(cancellationToken)){await using var q=c.CreateCommand();q.CommandText="SELECT SegmentId,SegmentIndex,CaptureMs,VisualState,ThumbnailContentType,ThumbnailLength,ThumbnailSha256,LastError,UpdatedAtUtc,ThumbnailObjectKey FROM DemoVisualSegment WHERE AssetId=$asset AND SourceKind=$source;";q.Parameters.AddWithValue("$asset",assetId.ToString("D"));q.Parameters.AddWithValue("$source",sourceKind);await using var r=await q.ExecuteReaderAsync(cancellationToken);while(await r.ReadAsync(cancellationToken)){var row=new VisualRow(Guid.Parse(r.GetString(0)),r.GetInt32(1),r.IsDBNull(2)?null:r.GetInt64(2),r.GetString(3),r.IsDBNull(4)?null:r.GetString(4),r.IsDBNull(5)?null:r.GetInt64(5),r.IsDBNull(6)?null:r.GetString(6),r.IsDBNull(7)?null:r.GetString(7),r.IsDBNull(8)?null:DemoSqliteDatabase.FromDb(r.GetString(8)),r.IsDBNull(9)?null:r.GetString(9));visual[row.Index]=row;}}
        return text.Segments.Select(s=>{visual.TryGetValue(s.SegmentIndex,out var v);return new VisualSegmentSnapshot(v?.Id??VisualSegmentIdentity.Create(assetId,sourceKind,s.SegmentIndex),assetId,sourceKind,s.SegmentIndex,s.StartMs,s.EndMs,s.PageNumber,s.Text,v?.CaptureMs,v?.State??VisualStates.Pending,!string.IsNullOrWhiteSpace(v?.ObjectKey),v?.ContentType,v?.Length,v?.Sha,v?.Error,v?.Updated);}).ToArray();
    }

    public async Task RegisterSegmentsAsync(Guid assetId,string sourceKind,IReadOnlyList<TextSegmentSnapshot> segments,bool visualEligible,string? unavailableReason,CancellationToken cancellationToken=default)
    {
        await EnsureSchemaAsync(cancellationToken);sourceKind=NormalizeSource(sourceKind);await using var c=await database.OpenAsync(cancellationToken);await using var tx=await c.BeginTransactionAsync(cancellationToken);
        await using(var delIndex=c.CreateCommand()){delIndex.Transaction=(SqliteTransaction)tx;delIndex.CommandText="DELETE FROM DemoVisualIndex WHERE SegmentId IN (SELECT SegmentId FROM DemoVisualSegment WHERE AssetId=$asset AND SourceKind=$source);";delIndex.Parameters.AddWithValue("$asset",assetId.ToString("D"));delIndex.Parameters.AddWithValue("$source",sourceKind);await delIndex.ExecuteNonQueryAsync(cancellationToken);}
        await using(var del=c.CreateCommand()){del.Transaction=(SqliteTransaction)tx;del.CommandText="DELETE FROM DemoVisualSegment WHERE AssetId=$asset AND SourceKind=$source;";del.Parameters.AddWithValue("$asset",assetId.ToString("D"));del.Parameters.AddWithValue("$source",sourceKind);await del.ExecuteNonQueryAsync(cancellationToken);}
        foreach(var s in segments.OrderBy(x=>x.SegmentIndex)){await using var q=c.CreateCommand();q.Transaction=(SqliteTransaction)tx;q.CommandText="INSERT INTO DemoVisualSegment(SegmentId,AssetId,SourceKind,SegmentIndex,StartMs,EndMs,PageNumber,VisualState,LastError,UpdatedAtUtc) VALUES($id,$asset,$source,$index,$start,$end,$page,$state,$error,$now);";q.Parameters.AddWithValue("$id",VisualSegmentIdentity.Create(assetId,sourceKind,s.SegmentIndex).ToString("D"));q.Parameters.AddWithValue("$asset",assetId.ToString("D"));q.Parameters.AddWithValue("$source",sourceKind);q.Parameters.AddWithValue("$index",s.SegmentIndex);q.Parameters.AddWithValue("$start",(object?)s.StartMs??DBNull.Value);q.Parameters.AddWithValue("$end",(object?)s.EndMs??DBNull.Value);q.Parameters.AddWithValue("$page",(object?)s.PageNumber??DBNull.Value);q.Parameters.AddWithValue("$state",visualEligible?VisualStates.Pending:VisualStates.Unavailable);q.Parameters.AddWithValue("$error",visualEligible?DBNull.Value:(object?)Short(unavailableReason??"No visual frame is available for this segment.",1000));q.Parameters.AddWithValue("$now",DemoSqliteDatabase.ToDb(DateTimeOffset.UtcNow));await q.ExecuteNonQueryAsync(cancellationToken);}await tx.CommitAsync(cancellationToken);
    }

    public async Task<VisualSegmentSnapshot> UpsertSegmentThumbnailAsync(Guid assetId,string sourceKind,int segmentIndex,long captureMs,Stream thumbnail,string contentType,CancellationToken cancellationToken=default)
    {
        await EnsureSchemaAsync(cancellationToken);sourceKind=NormalizeSource(sourceKind);contentType=NormalizeImageType(contentType);var id=VisualSegmentIdentity.Create(assetId,sourceKind,segmentIndex);var bytes=await ReadBoundedAsync(thumbnail,12L*1024*1024,cancellationToken);if(bytes.Length==0)throw new VisualSearchRequestException("thumbnail_empty","Generated segment thumbnail is empty.",422);var sha=Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant();var key=$"{_derivativesPrefix}/{assetId:N}/visual/{sourceKind}/{id:N}.jpg";await using(var s=new MemoryStream(bytes,false))await primary.WriteAsync(key,s,sha,cancellationToken);VisualEmbeddingDescriptor embedding;await using(var s=new MemoryStream(bytes,false))embedding=await provider.EmbedAsync(s,$"{id:N}.jpg",contentType,cancellationToken);Validate(embedding);await using var c=await database.OpenAsync(cancellationToken);await using var tx=await c.BeginTransactionAsync(cancellationToken);await using(var q=c.CreateCommand()){q.Transaction=(SqliteTransaction)tx;q.CommandText="UPDATE DemoVisualSegment SET CaptureMs=$capture,ThumbnailObjectKey=$key,ThumbnailContentType=$type,ThumbnailLength=$length,ThumbnailSha256=$sha,VisualState='Ready',LastError=NULL,UpdatedAtUtc=$now WHERE SegmentId=$id AND AssetId=$asset;";q.Parameters.AddWithValue("$capture",captureMs);q.Parameters.AddWithValue("$key",key);q.Parameters.AddWithValue("$type",contentType);q.Parameters.AddWithValue("$length",bytes.LongLength);q.Parameters.AddWithValue("$sha",sha);q.Parameters.AddWithValue("$now",DemoSqliteDatabase.ToDb(DateTimeOffset.UtcNow));q.Parameters.AddWithValue("$id",id.ToString("D"));q.Parameters.AddWithValue("$asset",assetId.ToString("D"));if(await q.ExecuteNonQueryAsync(cancellationToken)!=1)throw new VisualSearchRequestException("visual_segment_not_found","Visual segment was not registered.",404);}await UpsertIndexAsync(c,(SqliteTransaction)tx,assetId,id,"Segment",sourceKind,embedding,Serialize(embedding.Values),sha,cancellationToken);await tx.CommitAsync(cancellationToken);return (await ListSegmentsAsync(assetId,sourceKind,cancellationToken)).Single(x=>x.SegmentId==id);
    }

    public async Task IndexAssetAsync(Guid assetId,CancellationToken cancellationToken=default)
    {
        await EnsureSchemaAsync(cancellationToken);var original=await ReadOriginalAsync(assetId,cancellationToken)??throw new VisualSearchRequestException("primary_original_not_found","Primary original is unavailable.",404);if(!string.Equals(original.Kind,MediaKinds.Image,StringComparison.OrdinalIgnoreCase))throw new VisualSearchRequestException("visual_asset_type_not_supported","Asset-level visual indexing supports image originals.",415);var verified=await primary.VerifyAsync(original.Key,original.Sha,cancellationToken);if(!verified.Exists||!verified.ChecksumMatches||verified.Length!=original.Length)throw new VisualSearchRequestException("primary_original_verification_failed","Primary original verification failed before visual indexing.",503);VisualEmbeddingDescriptor embedding;await using(var s=await primary.OpenReadAsync(original.Key,cancellationToken))embedding=await provider.EmbedAsync(s,original.Name,ContentType(original.Name),cancellationToken);Validate(embedding);await using var c=await database.OpenAsync(cancellationToken);await using var tx=await c.BeginTransactionAsync(cancellationToken);await UpsertIndexAsync(c,(SqliteTransaction)tx,assetId,null,"Asset","original",embedding,Serialize(embedding.Values),original.Sha,cancellationToken);await tx.CommitAsync(cancellationToken);
    }

    public async Task<VisualThumbnailPayload?> OpenThumbnailAsync(Guid assetId,Guid segmentId,CancellationToken cancellationToken=default)
    {
        await EnsureSchemaAsync(cancellationToken);await using var c=await database.OpenAsync(cancellationToken);await using var q=c.CreateCommand();q.CommandText="SELECT ThumbnailObjectKey,ThumbnailContentType,ThumbnailLength,ThumbnailSha256 FROM DemoVisualSegment WHERE AssetId=$asset AND SegmentId=$segment AND VisualState='Ready';";q.Parameters.AddWithValue("$asset",assetId.ToString("D"));q.Parameters.AddWithValue("$segment",segmentId.ToString("D"));await using var r=await q.ExecuteReaderAsync(cancellationToken);if(!await r.ReadAsync(cancellationToken)||r.IsDBNull(0))return null;var key=r.GetString(0);var type=r.GetString(1);var length=r.GetInt64(2);var sha=r.GetString(3);await r.DisposeAsync();var verify=await primary.VerifyAsync(key,sha,cancellationToken);if(!verify.Exists||!verify.ChecksumMatches||verify.Length!=length)throw new VisualSearchRequestException("thumbnail_verification_failed","Segment thumbnail verification failed before delivery.",503);return new VisualThumbnailPayload(await primary.OpenReadAsync(key,cancellationToken),type,$"segment-{segmentId:N}.jpg",length,sha);
    }

    public async Task<VisualSearchResult> SearchAsync(Stream queryImage,string? fileName,string? contentType,int limit=30,CancellationToken cancellationToken=default)
    {
        await EnsureSchemaAsync(cancellationToken);var health=provider.Health;if(!health.IsReady)throw new VisualSearchRequestException("visual_search_unavailable",health.Detail,503);await EnsureImageIndexesAsync(cancellationToken);limit=Math.Clamp(limit,1,100);var query=await provider.EmbedAsync(queryImage,fileName,contentType,cancellationToken);Validate(query);var rows=new List<VisualSearchHit>();await using var c=await database.OpenAsync(cancellationToken);await using var q=c.CreateCommand();q.CommandText="""
            SELECT vi.AssetId,a.Title,a.MediaKind,a.OriginalFileName,vi.SegmentId,vi.SourceKind,vs.SegmentIndex,vs.StartMs,vs.EndMs,vs.PageNumber,vs.ThumbnailObjectKey,vi.VectorPayload,vi.Provider,vi.ModelId,vi.ModelVersion,vi.UpdatedAtUtc
            FROM DemoVisualIndex vi JOIN DemoAsset a ON a.AssetId=vi.AssetId LEFT JOIN DemoVisualSegment vs ON vs.SegmentId=vi.SegmentId
            WHERE vi.IsActive=1 AND vi.Provider=$provider AND vi.ModelId=$model AND vi.ModelVersion=$version AND vi.Dimensions=$dimensions;
            """;q.Parameters.AddWithValue("$provider",query.Provider);q.Parameters.AddWithValue("$model",query.ModelId);q.Parameters.AddWithValue("$version",query.ModelVersion);q.Parameters.AddWithValue("$dimensions",query.Dimensions);await using var r=await q.ExecuteReaderAsync(cancellationToken);while(await r.ReadAsync(cancellationToken)){var candidate=Deserialize((byte[])r[11],query.Dimensions);var kind=r.IsDBNull(2)?MediaKinds.FromFileName(r.IsDBNull(3)?null:r.GetString(3)):r.GetString(2);rows.Add(new VisualSearchHit(Guid.Parse(r.GetString(0)),r.GetString(1),kind,r.IsDBNull(4)?null:Guid.Parse(r.GetString(4)),r.GetString(5),r.IsDBNull(6)?null:r.GetInt32(6),r.IsDBNull(7)?null:r.GetInt64(7),r.IsDBNull(8)?null:r.GetInt64(8),r.IsDBNull(9)?null:r.GetInt32(9),Similarity(query.Values,candidate),!r.IsDBNull(10),r.GetString(12),r.GetString(13),r.GetInt32(14),DemoSqliteDatabase.FromDb(r.GetString(15))));}return new VisualSearchResult(rows.OrderByDescending(x=>x.Score).ThenByDescending(x=>x.UpdatedAtUtc).Take(limit).ToArray(),query.Provider,query.ModelId,query.ModelVersion,query.Dimensions,limit);
    }

    private async Task EnsureSchemaAsync(CancellationToken ct)
    {
        await database.EnsureInitializedAsync(ct);await using var c=await database.OpenAsync(ct);await using var q=c.CreateCommand();q.CommandText="""
            CREATE TABLE IF NOT EXISTS DemoVisualSegment(SegmentId TEXT PRIMARY KEY,AssetId TEXT NOT NULL,SourceKind TEXT NOT NULL,SegmentIndex INTEGER NOT NULL,StartMs INTEGER NULL,EndMs INTEGER NULL,PageNumber INTEGER NULL,CaptureMs INTEGER NULL,ThumbnailObjectKey TEXT NULL,ThumbnailContentType TEXT NULL,ThumbnailLength INTEGER NULL,ThumbnailSha256 TEXT NULL,VisualState TEXT NOT NULL,LastError TEXT NULL,UpdatedAtUtc TEXT NOT NULL,UNIQUE(AssetId,SourceKind,SegmentIndex),FOREIGN KEY(AssetId) REFERENCES DemoAsset(AssetId) ON DELETE CASCADE);
            CREATE TABLE IF NOT EXISTS DemoVisualIndex(VisualIndexId TEXT PRIMARY KEY,AssetId TEXT NOT NULL,SegmentId TEXT NULL,IndexScope TEXT NOT NULL,SourceKind TEXT NOT NULL,Provider TEXT NOT NULL,ModelId TEXT NOT NULL,ModelVersion INTEGER NOT NULL,Dimensions INTEGER NOT NULL,VectorPayload BLOB NOT NULL,SourceSha256 TEXT NOT NULL,IsActive INTEGER NOT NULL,CreatedAtUtc TEXT NOT NULL,UpdatedAtUtc TEXT NOT NULL,FOREIGN KEY(AssetId) REFERENCES DemoAsset(AssetId) ON DELETE CASCADE,FOREIGN KEY(SegmentId) REFERENCES DemoVisualSegment(SegmentId) ON DELETE CASCADE);
            CREATE UNIQUE INDEX IF NOT EXISTS UX_DemoVisualIndex_Logical ON DemoVisualIndex(AssetId,IFNULL(SegmentId,''),IndexScope,Provider,ModelId,ModelVersion);
            CREATE INDEX IF NOT EXISTS IX_DemoVisualIndex_Compatible ON DemoVisualIndex(Provider,ModelId,ModelVersion,Dimensions,IsActive);
            """;await q.ExecuteNonQueryAsync(ct);
    }

    private async Task EnsureImageIndexesAsync(CancellationToken ct)
    {
        var ids=new List<Guid>();await using(var c=await database.OpenAsync(ct)){await using var q=c.CreateCommand();q.CommandText="SELECT a.AssetId FROM DemoAsset a WHERE a.OriginalObjectKey IS NOT NULL AND COALESCE(a.MediaKind,'')='Image' AND NOT EXISTS(SELECT 1 FROM DemoVisualIndex vi WHERE vi.AssetId=a.AssetId AND vi.IndexScope='Asset' AND vi.IsActive=1) LIMIT 100;";await using var r=await q.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))ids.Add(Guid.Parse(r.GetString(0)));}foreach(var id in ids){try{await IndexAssetAsync(id,ct);}catch(VisualSearchRequestException){}}
    }
    private async Task<AssetTextSnapshot?> ReadTextAsync(Guid id,string source,CancellationToken ct){await using var c=await database.OpenAsync(ct);await using var q=c.CreateCommand();q.CommandText="SELECT Language,TextValue,ContentSha256,SegmentsJson,UpdatedAtUtc FROM DemoAssetText WHERE AssetId=$asset AND SourceKind=$source;";q.Parameters.AddWithValue("$asset",id.ToString("D"));q.Parameters.AddWithValue("$source",source);await using var r=await q.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))return null;var segments=JsonSerializer.Deserialize<TextSegmentSnapshot[]>(r.GetString(3))??[];return new AssetTextSnapshot(id,source,r.IsDBNull(0)?null:r.GetString(0),r.GetString(1),r.IsDBNull(2)?null:r.GetString(2),segments,DemoSqliteDatabase.FromDb(r.GetString(4)));}
    private async Task<Original?> ReadOriginalAsync(Guid id,CancellationToken ct){await using var c=await database.OpenAsync(ct);await using var q=c.CreateCommand();q.CommandText="SELECT OriginalObjectKey,OriginalFileName,OriginalLength,OriginalSha256,MediaKind FROM DemoAsset WHERE AssetId=$id;";q.Parameters.AddWithValue("$id",id.ToString("D"));await using var r=await q.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct)||r.IsDBNull(0))return null;var name=r.GetString(1);return new Original(r.GetString(0),name,r.GetInt64(2),r.GetString(3),r.IsDBNull(4)?MediaKinds.FromFileName(name):r.GetString(4));}
    private static async Task UpsertIndexAsync(SqliteConnection c,SqliteTransaction tx,Guid assetId,Guid? segmentId,string scope,string source,VisualEmbeddingDescriptor e,byte[] vector,string sha,CancellationToken ct){await using(var off=c.CreateCommand()){off.Transaction=tx;off.CommandText="UPDATE DemoVisualIndex SET IsActive=0,UpdatedAtUtc=$now WHERE AssetId=$asset AND IFNULL(SegmentId,'')=IFNULL($segment,'') AND IndexScope=$scope AND IsActive=1 AND (Provider<>$provider OR ModelId<>$model OR ModelVersion<>$version OR Dimensions<>$dimensions);";off.Parameters.AddWithValue("$now",DemoSqliteDatabase.ToDb(DateTimeOffset.UtcNow));off.Parameters.AddWithValue("$asset",assetId.ToString("D"));off.Parameters.AddWithValue("$segment",segmentId is Guid s?s.ToString("D"):DBNull.Value);off.Parameters.AddWithValue("$scope",scope);off.Parameters.AddWithValue("$provider",e.Provider);off.Parameters.AddWithValue("$model",e.ModelId);off.Parameters.AddWithValue("$version",e.ModelVersion);off.Parameters.AddWithValue("$dimensions",e.Dimensions);await off.ExecuteNonQueryAsync(ct);}await using var q=c.CreateCommand();q.Transaction=tx;q.CommandText="INSERT INTO DemoVisualIndex(VisualIndexId,AssetId,SegmentId,IndexScope,SourceKind,Provider,ModelId,ModelVersion,Dimensions,VectorPayload,SourceSha256,IsActive,CreatedAtUtc,UpdatedAtUtc) VALUES($id,$asset,$segment,$scope,$source,$provider,$model,$version,$dimensions,$vector,$sha,1,$now,$now) ON CONFLICT DO UPDATE SET SourceKind=excluded.SourceKind,Dimensions=excluded.Dimensions,VectorPayload=excluded.VectorPayload,SourceSha256=excluded.SourceSha256,IsActive=1,UpdatedAtUtc=excluded.UpdatedAtUtc;";q.Parameters.AddWithValue("$id",Guid.NewGuid().ToString("D"));q.Parameters.AddWithValue("$asset",assetId.ToString("D"));q.Parameters.AddWithValue("$segment",segmentId is Guid seg?seg.ToString("D"):DBNull.Value);q.Parameters.AddWithValue("$scope",scope);q.Parameters.AddWithValue("$source",source);q.Parameters.AddWithValue("$provider",e.Provider);q.Parameters.AddWithValue("$model",e.ModelId);q.Parameters.AddWithValue("$version",e.ModelVersion);q.Parameters.AddWithValue("$dimensions",e.Dimensions);q.Parameters.AddWithValue("$vector",vector);q.Parameters.AddWithValue("$sha",sha);q.Parameters.AddWithValue("$now",DemoSqliteDatabase.ToDb(DateTimeOffset.UtcNow));await q.ExecuteNonQueryAsync(ct);}
    private static void Validate(VisualEmbeddingDescriptor e){if(e.Dimensions<=0||e.Dimensions>8192||e.Values.Count!=e.Dimensions||e.Values.Any(float.IsNaN)||e.Values.Any(float.IsInfinity))throw new VisualSearchRequestException("visual_embedding_invalid","Visual provider returned an invalid embedding.",503);}
    private static byte[] Serialize(IReadOnlyList<float> values){var a=values as float[]??values.ToArray();var b=new byte[a.Length*4];Buffer.BlockCopy(a,0,b,0,b.Length);return b;}
    private static float[] Deserialize(byte[] bytes,int dimensions){if(bytes.Length!=dimensions*4)throw new VisualSearchRequestException("visual_index_corrupt","Stored visual index is corrupt.",503);var a=new float[dimensions];Buffer.BlockCopy(bytes,0,a,0,bytes.Length);return a;}
    private static double Similarity(IReadOnlyList<float>a,IReadOnlyList<float>b){double dot=0,aa=0,bb=0;for(var i=0;i<a.Count&&i<b.Count;i++){dot+=a[i]*b[i];aa+=a[i]*a[i];bb+=b[i]*b[i];}if(aa<=1e-12||bb<=1e-12)return 0;return Math.Clamp((dot/(Math.Sqrt(aa)*Math.Sqrt(bb))+1)/2,0,1);}
    private static async Task<byte[]> ReadBoundedAsync(Stream s,long max,CancellationToken ct){await using var m=new MemoryStream();var b=new byte[65536];long total=0;while(true){var n=await s.ReadAsync(b.AsMemory(0,b.Length),ct);if(n==0)break;total+=n;if(total>max)throw new VisualSearchRequestException("thumbnail_too_large","Generated thumbnail is too large.",413);await m.WriteAsync(b.AsMemory(0,n),ct);}return m.ToArray();}
    private static string NormalizeSource(string? s){var v=s?.Trim().ToLowerInvariant();if(string.IsNullOrWhiteSpace(v)||v.Length>40)throw new VisualSearchRequestException("visual_source_invalid","Visual source kind is invalid.");return v;}
    private static string NormalizeImageType(string? s){var v=s?.Split(';',2)[0].Trim().ToLowerInvariant();return v is "image/jpeg" or "image/png" or "image/bmp" or "image/gif" or "image/tiff" or "image/webp"?v:throw new VisualSearchRequestException("image_type_not_supported","Image type is not supported.",415);}
    private static string ContentType(string n)=>Path.GetExtension(n).ToLowerInvariant() switch{".jpg" or ".jpeg"=>"image/jpeg",".png"=>"image/png",".bmp"=>"image/bmp",".gif"=>"image/gif",".tif" or ".tiff"=>"image/tiff",".webp"=>"image/webp",_=>"application/octet-stream"};
    private static string CleanPrefix(string? s,string fallback){var v=string.IsNullOrWhiteSpace(s)?fallback:s.Trim().Trim('/','\\');return v.Length==0?fallback:v;}
    private static string Short(string s,int max)=>s.Length<=max?s:s[..max];
    private sealed record VisualRow(Guid Id,int Index,long? CaptureMs,string State,string? ContentType,long? Length,string? Sha,string? Error,DateTimeOffset? Updated,string? ObjectKey);
    private sealed record Original(string Key,string Name,long Length,string Sha,string Kind);
}